openapi: 3.0.0

info:
  title: Essence Enclave API
  description: API documentation for Essence Enclave backend
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: Development server

tags:
  - name: Auth
    description: Authentication endpoints
  - name: Users
    description: User management
  - name: Products
    description: Products management
  - name: Cart
    description: Cart management

paths:
  /api/auth/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterUser"
      responses:
        201:
          description: User registered successfully
        400:
          description: Validation error

  /api/auth/login:
    post:
      tags:
        - Auth
      summary: Login into your account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUser"
      responses:
        200:
          description: Logged in successfully
        400:
          description: Validation error

  /api/auth/logout:
    get:
      tags:
        - Auth
      summary: Logout your account
      responses:
        200:
          description: Logged out successfully
        400:
          description: Validation error

  /api/auth/user:
    get:
      tags:
        - Users
      summary: Fetched user informations
      responses:
        200:
          description: User details fetched successfully
        400:
          description: Validation error

  /api/auth/refresh:
    get:
      tags:
        - Auth
      summary: Refresh Token
      responses:
        200:
          description: Token generated successfully
        400:
          description: Validation error

  /api/products/all:
    get:
      tags:
        - Products
      summary: Fetch all products in db
      responses:
        200:
          description: Products fetched successfully
        400:
          description: Product not found

  /api/products/{productId}:
    get:
      tags:
        - Products
      summary: Get a product by its ID
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: Product ID
      responses:
        200:
          description: Product fetched successfully
        404:
          description: Product not found

  /api/cart/add:
    post:
      tags:
        - Cart
      summary: Add item(s) to cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cart"
      responses:
        200:
          description: Item(s) added to cart successfully
        404:
          description: Unable to add item to the cart

components:
  schemas:
    CartItem:
      type: object
      required:
        - product
        - quantity
      properties:
        product:
          type: string
          minLength: 1
        quantity:
          type: number
          minimum: 1
          default: 1

    Cart:
      type: object
      required:
        - item
      properties:
        item:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/CartItem'
        totalPrice:
          type: number
          minimum: 0

    RegisterUser:
      type: object
      required:
        - firstName
        - lastName
        - email
        - password
      properties:
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        email:
          type: string
          example: johndoe@gmail.com
        password:
          type: string
          example: secret123
        phoneNumber:
          type: string
          example: "08012345678"

    LoginUser:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          example: johndoe@gmail.com
        password:
          type: string
          example: secret123


